name: E2E Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
      
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@main
        if: always() && job.status != 'cancelled'
        with:
          node-version: 14.x

      - name: install dependencies
        if: always() && job.status != 'cancelled'
        run: yarn --frozen-lockfile

      - name: build
        if: always() && job.status != 'cancelled'
        run: yarn build

      - name: run tests
        run: DEBUG=pw:api npx playwright test playwright/specs/ -c playwright/playwright.config.ts