name: E2E Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
      
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@main
        if: always() && job.status != 'cancelled'
        with:
          node-version: 14.x

      - name: Install Xvfb (required for Electron to work)
        run: sudo apt-get install xvfb

      - name: Install dependencies
        if: always() && job.status != 'cancelled'
        run: yarn --frozen-lockfile

      - name: Build
        if: always() && job.status != 'cancelled'
        run: yarn build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: DEBUG=pw:browser xvfb-run npx playwright test playwright/specs/ -c playwright/playwright.config.ts

      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1