name: Playwright E2E Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
      
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Electron App
        run: yarn build

      - name: Run Playwright tests
        run: DEBUG=pw:api xvfb-run npx playwright test playwright/specs/ -c playwright/playwright.config.ts

      - name: Upload ci suggested screenshots
        uses: actions/upload-artifact@v2
        with:
          name: ci-screenshots
          path: screenshots/