name: Screenshot Tests
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ui-tests-linux:
    name: ui tests (${{ matrix.os }})
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
      - uses: actions/setup-node@main
        with:
          node-version: 14.x
      - uses: actions/setup-python@v1
        with:
          python-version: "2.7.x"
      - name: install linux dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
      - name: install and switch to GCC 5.4
        if: matrix.os == 'ubuntu-20.04'
        run: ./tools/g++-5.4/install.sh
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        env:
          JOBS: max
        run: yarn --frozen-lockfile
      - name: install operating system dependencies
        run: npx playwright install-deps
      - name: build electron app
        run: yarn build
      - name: run ui tests
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb-run yarn playwright-ci
      - name: run ui tests
        if: matrix.os != 'ubuntu-20.04'
        run: yarn playwright-ci
      - name: upload ci suggested screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ matrix.os }}
          path: |
            playwright/artifacts/test-results
            playwright/artifacts/videos
