name: Screenshot Tests
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ui-tests:
    name: ui tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      # - name: install linux dependencies
      #   if: matrix.os == 'ubuntu-20.04'
      #   run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
      # - name: install and switch to GCC 5.4
      #   if: matrix.os == 'ubuntu-20.04'
      #   run: ./tools/g++-5.4/install.sh
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        env:
          JOBS: max
        run: yarn --frozen-lockfile
      - name: build electron app
        run: yarn build
      - name: install operating system dependencies
        run: npx playwright install-deps
      - name: prepare graphical environment (xvfb-run npm ci)
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb-run yarn playwright
        env:
          DISPLAY: :99
          ALLURE_RESULTS_DIR: playwright/artifacts/allure-results
      - name: prepare graphical environment (xvfb-run npm ci)
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb-run yarn playwright playwright/specs/onboarding.spec.ts
        env:
          DISPLAY: :99
          ALLURE_RESULTS_DIR: playwright/artifacts/allure-results
      - name: prepare graphical environment (xvfb-run npx + onboarding)
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb-run npx playwright test playwright/specs/onboarding.spec.ts --config=playwright/playwright.config.ts
        env:
          DISPLAY: :99
          ALLURE_RESULTS_DIR: playwright/artifacts/allure-results
      - name: prepare graphical environment (xvfb start)
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb start
        env:
          DISPLAY: :99
          ALLURE_RESULTS_DIR: playwright/artifacts/allure-results
      - name: run ui tests (xvfb start)
        if: matrix.os == 'ubuntu-20.04'
        run: yarn playwright-ci
        env:
          ALLURE_RESULTS_DIR: playwright/artifacts/allure-results
      - name: run ui tests
        run: yarn playwright-ci
        env:
          DEBUG: pw:api
      - name: upload ci suggested screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ matrix.os }}
          path: |
            playwright/artifacts/test-results
            playwright/artifacts/videos
