name: UI tests
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ui-tests:
    name: UI tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install operating system dependencies
        run: npx playwright install-deps
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        env:
          JOBS: max
        run: yarn --frozen-lockfile
      - name: run code checks
        if: always()
        run: yarn ci 2> >(tee lint.txt)
      - name: build electron app
        env:
          INSTRUMENT_BUILD: true
        run: yarn build
      - name: tests
        if: always()
        run: yarn test 2> >(tee jest.txt)
      - name: run ui tests (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: xvfb-run --auto-servernum -- yarn playwright
      - name: run ui tests (macOS & Windows)
        if: matrix.os != 'ubuntu-20.04'
        run: yarn playwright
      - name: upload diffs to imgur
        if: always()
        uses: ./.github/actions/upload-images
        id: imgur
        with:
          path: playwright/artifacts/test-results
      - name: save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - name: upload tests data
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: report-${{ matrix.os }}
          path: |
            lint.txt
            jest.txt
            pr/NR
      - name: upload ci suggested screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results-${{ matrix.os }}
          path: |
            playwright/artifacts/test-results
            playwright/artifacts/html-report
            playwright/artifacts/coverage
            playwright/artifacts/videos
